version: '3'

services:
  node:
    build: .
    container_name: node
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/api-nestjs
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - REDIS_HOST=redis
    depends_on:
      - mysql_db
      - redis

  mysql_db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_nestjs
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
